fix union sql. add parentheses.
scalikejdbc/scalikejdbc pull request #1398
Opened 2021-12-13 21:52 UTC by keyno63

fix #1391

- Add round bracket when using union syntax.
- A reason a function is branched is mysql seems to disallow double round bracket (even so postgres and h2 allow it.)

2021-12-26 03:00 UTC, seratch requested changes
Adding round brackets for subquery parts should be fine as the CI builds pass with all the supported databases.

2021-12-26 05:51 UTC, keyno63 commented on scalikejdbc-interpolation/src/main/scala/scalikejdbc/QueryDSLFeature.scala
> +    private def considerRoundBracket(sqlQuery: SQLSyntax): SQLSyntax =
Thanks for reviewing.

I changed the function name.
6d2d16d409ce02158461e28f776c9b00cbf25df2

2021-12-26 05:55 UTC, keyno63 commented on scalikejdbc-interpolation/src/main/scala/scalikejdbc/QueryDSLFeature.scala
> +      if (sqlQuery.value.startsWith("(") && sqlQuery.value.endsWith(")"))
I did not notice it.
I fixed to trimming spaces.
6d2d16d409ce02158461e28f776c9b00cbf25df2

2022-01-28 05:56 UTC, seratch approved these changes
Look good to me! We can merge this PR after waiting for others' feedback for a few more days.

2022-03-04 13:18 UTC, keyno63 commented
Thank you for reviewing this PR.

 I'm excited that my work may contribute to a project I love!

2022-03-06 08:55 UTC, merged